import { createRoot } from 'react-dom/client'
import './styles.css'
import { Logo } from '@pmndrs/branding'
import { App } from './App.js'

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

function Root() {
  return (
    <>
      <App/>
      <div style={{ position: 'absolute', pointerEvents: 'none', top: 0, left: 0, width: '100vw', height: '100vh' }}>
        <a href="" style={{ position: 'absolute', bottom: 40, left: 90, fontSize: '13px' }}>
          CYBERZEE
          <br />
          PRESENTS

        </a>
        <img src="/logo2.png" style={{ width: '40px', height: '40px',position: 'absolute', bottom: 35, left: 50, fontSize: '13px',borderRadius: '50%', marginRight: '5px' }} />

        <div style={{ position: 'absolute', bottom: 40, right: 40, fontSize: '13px' }}>16/03/2024</div>
        <a style={{ position: 'absolute', top: 40, left: 40, fontSize: '13px' }} href="#">
          MITILENCE
        </a>
      </div>{' '}
    </>
  )
}
createRoot(document.getElementById('root')).render(<Root />)
